# fly.toml app configuration file generated for thi on 2024-04-06T13:32:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'thi'
primary_region = 'hkg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
